[package]
name = "imxrt106x-iomuxc"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"

[dependencies.imxrt-iomuxc]
path = ".."

[build-dependencies.imxrt-iomuxc-build]
path = "../imxrt-iomuxc-build"