[package]
name = "tools"
version = "0.1.0"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
